### ISSUE TITLE
Python3 wont show plot of demo 

### ISSUE THREAD

**Issue by sriranjansony** [cslotboom/hysteresis#22]
Hello,

I ran the example demo code but I do not see any plot. The file compiles fine. Could you please tell me why am I not able to see any graphs?

**Comment by cslotboom** [comment]
Hey - I'm going to assume you have matplotlib installed in your environment - are there any errors? How are you running the file?

**Comment by sriranjansony** [comment]
I have matplotlib installed and running. When I run the file saying $python3 demo1.py .I do not get any errors and it compiles fine but at the same time I do not see any plots displayed.

**Comment by cslotboom** [comment]
I see - you'll have to import matplotlib and issue a "show" command after the plot command.
I separate the "show" command from the plot command, because you might want to modify your graphs before showing them. I might look into doing it a different way in the future.

You could modify the demo code as follows - the show.plot() is the most important change.
However, I'm also returning the matplotlib figure elements that hysteresis creates to be more clear. You can interact with these like you would any matplotlib figure.

Let me know if this solves your issue.

```
import numpy as np
import hysteresis as hys
import matplotlib.pyplot as plt

t = np.linspace(0,4,1000)*np.pi
x = np.sin(t)
y = np.cos(t)*t

xy = np.column_stack([x,y])

myHys = hys.Hysteresis(xy)
fig, ax = myHys.initFig()
line = myHys.plot(plotCycles = True)
plt.show()
```

**Comment by sriranjansony** [comment]
Thank you for the update.When I initially ran this code there was an error showing that fig is not defined. So I removed fig and now I can see the plot. Thanks for the correction.
